name: phidlfem
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - fenics-dolfinx=0.7.3
  - mpich=4.2.0
  - pyvista
  - gmsh
  - python-gmsh
  - pip
  - numpy
  - scipy
  - pip:
    - phidl
